services:
  mongo:
    image: mongo
    container_name: mongo_2
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    command: ["mongod", "--quiet", "--logpath", "/dev/null"]
    env_file:
      - .env
    volumes:
      - mongo-data:/data/mongod.conf:/etc/mongod.conf
      - mongo-data:/data/db

  app:
    build: ./app
    container_name: my_node_app_2
    depends_on:
      - mongo
    ports:
      - 4000:4000
    volumes:
      - ./app:/app
      - /app/node_modules
    command: npm run dev
    environment:
      APP_NAME: DockerApp
      PORT: 4000
      MONGO_URI: mongodb://root:example@mongo:27017/vestibulario?authSource=admin
      SECRET: c388f7fc6034d79f59228e703230180128262defe52a8f7971dbddec1d2f96b8
        - CHOKIDAR_USEPOLLING=true

  frontend:
    build: ./vestibulario-react
    container_name: vestibulario_react
    volumes:
       - ./:/vestibulario-react:delegated
       - /node_modules
    ports:
      - "3000:3000"
    depends_on:
      - app
    command: npm start
    environment:
      - CHOKIDAR_USEPOLLING=true


volumes:
  mongo-data: