services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    command: ["mongod", "--quiet", "--logpath", "/dev/null"]
    env_file:
      - .env
    volumes:
      - mongo-data:/data/mongod.conf:/etc/mongod.conf
      - mongo-data:/data/db

  app:
    build: .
    container_name: my_node_app
    depends_on:
      - mongo
    ports:
      - 4000:4000
    environment:
      APP_NAME: DockerApp
      PORT: 4000
      MONGO_URI: mongodb://root:example@mongo:27017/vestibulario?authSource=admin


volumes:
  mongo-data: