services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/mongod.conf:/etc/mongod.conf
      - mongo-data:/data/db

  app:
    build: .
    container_name: my_node_app
    depends_on:
      - mongo
    ports:
      - 3000:3000
    environment:
      APP_NAME: DockerApp
      PORT: 3000
      MONGO_URI: mongodb://root:example@127.0.0.1:27017?authSource=admin

volumes:
  mongo-data: